apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-http
  namespace: lcf-k8s-cicd
  labels:
    app: jenkins
    criticity: high
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
      name: jenkins-url