apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-jnlp
  namespace: lcf-k8s-cicd
  labels:
    app: jenkins
    criticity: high
spec:
  selector:
    app: jenkins-server
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: jenkins-http-interne
    - port: 50000
      targetPort: 50000
      name: jenkins-jnlp