apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod-pvc
  namespace: lcf-k8s-volume
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sh', '-c', 'while true; do echo "log at $(date)" >> /opt/app/logs.txt; sleep 1; done']
    resources:
      limits:
        cpu: 400m
        memory: 400Mi
      requests:
        cpu: 200m
        memory: 200Mi
    volumeMounts:
    - name: vol-pvc
      mountPath: /opt/app
  volumes:
  - name: vol-pvc
    persistentVolumeClaim:
      claimName: pvc-hostpath