apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath01
spec:
  storageClassName: "hostpath"
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 6Gi
  hostPath:
    path: /Users/k6sy/Projects/lecloudfacile-k8s-bootcamp/05-session-volumes/path01/mypv

# Attention à changer le path selon votre environnement