apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath02
  namespace: lcf-k8s-volume
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi