# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.29.0
controlPlaneEndpoint: "srvlcfmaster01.lab.io:6443"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1