#Request: Ce que demande un pod / Limit: Ce qu'il ne peut pas dépasser
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-lcf-limit-range

---
apiVersion: v1
kind: LimitRange
metadata:
  name: memory-cpu-limit-range
  namespace: k8s-lcf-limit-range
spec:
  limits:
  - default:
      cpu: 1
      memory: 512Mi
    defaultRequest:
      cpu: "0.5"
      memory: 256Mi
    type: Container
