apiVersion: v1
kind: Pod
metadata:
  name: lrpod2
  namespace: k8s-lcf-limit-range
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: lrpod2
    resources:
      limits:
        cpu: "2"
        memory: 512Mi
      requests:
        cpu: "1"
        memory: 2Gi