apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cert
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: kalidou.harouna.sy@gmail.com
    privateKeySecretRef:
      name: myingress-lcf-io
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx