apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonar-logs
  namespace: discovery
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi