apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  namespace: discovery
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      name: sonar-port