apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lcf
  name: lcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lcf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lcf
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
