apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  namespace: lcf-k8s-secret
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb:11.4
    resources:
      limits:
        cpu: 400m
        memory: 400Mi
      requests:
        cpu: 200m
        memory: 200Mi
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mysql-secret
    volumeMounts:
    - name: mariadb-data
      mountPath: /var/lib/mysql
    - name: mariadb-credential
      mountPath: /mysql/password
  volumes:
  - name: mariadb-credential
    secret:
      secretName: mariadb-secret
  - name: mariadb-data
    persistentVolumeClaim:
      claimName: mariadb-pvc