apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  namespace: lcf-k8s-secret
spec:
  containers:
  - name: phpmyadmin
    image: phpmyadmin
    resources:
      limits:
        cpu: 400m
        memory: 400Mi
      requests:
        cpu: 200m
        memory: 200Mi
    env:
    - name: PMA_HOST
      value: mariadb-service