apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  storageClassName: "hostpath"
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /Users/k6sy/Projects/lecloudfacile-k8s-bootcamp/05-session-volume-cm-secret/path01/mariadb

# Attention à changer le path selon votre environnement