apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: lcf-k8s-secret
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi