apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: lcf-k8s-secret
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: mariadb-port