apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: lcf-k8s-secret
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
      name: phpmyadmin-port